#! /usr/bin/env bash
echo -e "creating bucket...\n"

#Check if there is at least one argument [bucket name]
if [ -z "$1" ]; then
    echo "No bucket name variable provided. eg. ./bucket my-bucket-name"
    exit 1
fi


aws s3api create-bucket --bucket $1 \
--query Location \
--output text