#! /usr/bin/env bash

echo "deleting objects..."

#Exit immediately if any command returns a non-zero status
set -e

#Check if there is at least one argument [bucket name]
if [ -z "$1" ]; then
    echo "No bucket name variable provided. eg. ./bucket my-bucket-name"
    exit 1
fi



BUCKET_NAME=$1
DELETE_JSON='/tmp/delete_objects.json'

 aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > $DELETE_JSON

# uncomment below to check contents of file before deleting
# echo "$(<$DELETE_JSON)"

aws s3api delete-objects --bucket $BUCKET_NAME --delete "file:///$DELETE_JSON"