#! /usr/bin/env bash
echo "deleting bucket [$1]..."

#Check if there is at least one argument
if [ -z "$1" ]; then
    echo "No bucket name variable provided. eg. ./bucket my-bucket-name"
    exit 1
fi


aws s3api delete-bucket --bucket $1 \
--query Location \
--output text