#! /usr/bin/env bash

echo "listing objects..."

#Exit immediately if any command returns a non-zero status
set -e

#Check if there is at least one argument [bucket name]
if [ -z "$1" ]; then
    echo "no bucket name variable provided. eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}'