#! /usr/bin/env bash

echo "putting an object..."

#Exit immediately if any command returns a non-zero status
set -e

#Check if there is at least one argument [bucket name]
if [ -z "$1" ]; then
    echo -e "\nno bucket name provided. eg. ./bucket my-bucket-name"
    exit 1
fi



#Check if there is at least one argument [bucket name]
if [ -z "$2" ]; then
    echo -e "\nno filename provided!"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY