#! /usr/bin/env bash
# this script will upload to the bucket (argument 1),
# a randomly created number of 5-10 files  (argument 2)

echo "syncing..."

#Exit immediately if any command returns a non-zero status
set -e

#Check if there is at least one argument [bucket name]
if [ -z "$1" ]; then
    echo "No bucket name variable provided. eg. ./bucket my-bucket-name"
    exit 1
fi



#Check if there is at least one argument [bucket name]
if [ -z "$2" ]; then
    echo "No filename prefix provided..."
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2


# where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"



# remove folder if it already exists
rm -r $OUTPUT_DIR  || \

#otherwise create the output directory
mkdir -p $OUTPUT_DIR

# generate a random ceiling number
# determines how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX$i.txt"

    # Generate random data and write to file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files